[phases.setup]
nixPkgs = ["python310", "pip"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "python app.py"

[variables]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"
